version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend/:/backend/
    command: bash -c "alembic upgrade head && uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./frontend/:/frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"

volumes:
  postgres_data:

